### ISSUE TITLE
issues when using obisdian table editor core plugin

### ISSUE THREAD

**Issue by KraXen72** [0x-DLN/obsidian-table-checkboxes#9]
first issue: obsidian autocompletes the ` ]` of `- [ ]` after you type `- [`, so it's unintuitive to have to type ` ]` when it's already there.
second issue: even when you type ` ]`, the checkbox gets inserted but the `]` stays there:

https://github.com/DylanGiesberts/obsidian-table-checkboxes/assets/21956756/809b185f-0f1b-4d9b-94ea-65afdc750191

**Comment by DylanGiesberts** [comment]
Second issue should be fixed in [2.0.7](https://github.com/DylanGiesberts/obsidian-table-checkboxes/releases/tag/2.0.7).

First issue is tricky, since my event seems to go off before Obsidian's does, so it's hard to tell if a user is typing a checkbox, or just a dash `-`.

I'll leave the issue open for now, might come back to it at some point

**Comment by 0x-DLN** [comment]
Should be fixed in 3.0.0
